# Simple workflow for running prettier
name: Prettier

on:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{json,html}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: \[WORKFLOW\] Apply formatting changes
          branch: ${{ github.head_ref }}

