name: Presentation Workflow
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  rust-workflow:
    uses: ./.github/workflows/cargo.yml
  prettier-workflow:
    needs: rust-workflow
    uses: ./.github/workflows/prettier.yml
  static-workflow:
    needs: prettier-workflow
    uses: ./.github/workflows/static.yml
